# coding: utf-8

# flake8: noqa
"""
    OpenProject API V3 (Stable)

    You're looking at the current **stable** documentation of the OpenProject APIv3. If you're interested in the current development version, please go to [github.com/opf](https://github.com/opf/openproject/tree/dev/docs/api/apiv3).  ## Introduction  The documentation for the APIv3 is written according to the [OpenAPI 3.1 Specification](https://swagger.io/specification/). You can either view the static version of this documentation on the [website](https://www.openproject.org/docs/api/introduction/) or the interactive version, rendered with [OpenAPI Explorer](https://github.com/Rhosys/openapi-explorer/blob/main/README.md), in your OpenProject installation under `/api/docs`. In the latter you can try out the various API endpoints directly interacting with our OpenProject data. Moreover you can access the specification source itself under `/api/v3/spec.json` and `/api/v3/spec.yml` (e.g. [here](https://community.openproject.org/api/v3/spec.yml)).  The APIv3 is a hypermedia REST API, a shorthand for \"Hypermedia As The Engine Of Application State\" (HATEOAS). This means that each endpoint of this API will have links to other resources or actions defined in the resulting body.  These related resources and actions for any given resource will be context sensitive. For example, only actions that the authenticated user can take are being rendered. This can be used to dynamically identify actions that the user might take for any given response.  As an example, if you fetch a work package through the [Work Package endpoint](https://www.openproject.org/docs/api/endpoints/work-packages/), the `update` link will only be present when the user you authenticated has been granted a permission to update the work package in the assigned project.  ## HAL+JSON  HAL is a simple format that gives a consistent and easy way to hyperlink between resources in your API. Read more in the following specification: [https://tools.ietf.org/html/draft-kelly-json-hal-08](https://tools.ietf.org/html/draft-kelly-json-hal-08)  **OpenProject API implementation of HAL+JSON format** enriches JSON and introduces a few meta properties:  - `_type` - specifies the type of the resource (e.g.: WorkPackage, Project) - `_links` - contains all related resource and action links available for the resource - `_embedded` - contains all embedded objects  HAL does not guarantee that embedded resources are embedded in their full representation, they might as well be partially represented (e.g. some properties can be left out). However in this API you have the guarantee that whenever a resource is **embedded**, it is embedded in its **full representation**.  ## API response structure  All API responses contain a single HAL+JSON object, even collections of objects are technically represented by a single HAL+JSON object that itself contains its members. More details on collections can be found in the [Collections Section](https://www.openproject.org/docs/api/collections/).  ## Authentication  The API supports the following authentication schemes:  * Session-based authentication * API tokens     * passed as Bearer token     * passed via Basic auth * OAuth 2.0     * using built-in authorization server     * using an external authorization server (RFC 9068)  Depending on the settings of the OpenProject instance many resources can be accessed without being authenticated. In case the instance requires authentication on all requests the client will receive an **HTTP 401** status code in response to any request.  Otherwise unauthenticated clients have all the permissions of the anonymous user.  ### Session-based authentication  This means you have to login to OpenProject via the Web-Interface to be authenticated in the API. This method is well-suited for clients acting within the browser, like the Angular-Client built into OpenProject.  In this case, you always need to pass the HTTP header `X-Requested-With \"XMLHttpRequest\"` for authentication.  ### API token as bearer token  Users can authenticate towards the API v3 using an API token as a bearer token.  For example:  ```shell API_KEY=opapi-2519132cdf62dcf5a66fd96394672079f9e9cad1 curl -H \"Authorization: Bearer $API_KEY\" https://community.openproject.org/api/v3/users/42 ```  Users can generate API tokens on their account page.  ### API token through Basic Auth  API tokens can also be used with basic auth, using the user name `apikey` (NOT your login) and the API token as the password.  For example:  ```shell API_KEY=opapi-2519132cdf62dcf5a66fd96394672079f9e9cad1 curl -u apikey:$API_KEY https://community.openproject.org/api/v3/users/42 ```  ### OAuth 2.0 authentication  OpenProject allows authentication and authorization with OAuth2 with *Authorization code flow*, as well as *Client credentials* operation modes.  To get started, you first need to register an application in the OpenProject OAuth administration section of your installation. This will save an entry for your application with a client unique identifier (`client_id`) and an accompanying secret key (`client_secret`).  You can then use one the following guides to perform the supported OAuth 2.0 flows:  - [Authorization code flow](https://oauth.net/2/grant-types/authorization-code)  - [Authorization code flow with PKCE](https://doorkeeper.gitbook.io/guides/ruby-on-rails/pkce-flow), recommended for clients unable to keep the client_secret confidential  - [Client credentials](https://oauth.net/2/grant-types/client-credentials/) - Requires an application to be bound to an impersonating user for non-public access  ### OAuth 2.0 using an external authorization server  There is a possibility to use JSON Web Tokens (JWT) generated by an OIDC provider configured in OpenProject as a bearer token to do authenticated requests against the API. The following requirements must be met:  - OIDC provider must be configured in OpenProject with **jwks_uri** - JWT must be signed using RSA algorithm - JWT **iss** claim must be equal to OIDC provider **issuer** - JWT **aud** claim must contain the OpenProject **client ID** used at the OIDC provider - JWT **scope** claim must include a valid scope to access the desired API (e.g. `api_v3` for APIv3) - JWT must be actual (neither expired or too early to be used) - JWT must be passed in Authorization header like: `Authorization: Bearer {jwt}` - User from **sub** claim must be linked to OpenProject before (e.g. by logging in), otherwise it will be not authenticated  In more general terms, OpenProject should be compliant to [RFC 9068](https://www.rfc-editor.org/rfc/rfc9068) when validating access tokens.  ### Why not username and password?  The simplest way to do basic auth would be to use a user's username and password naturally. However, OpenProject already has supported API keys in the past for the API v2, though not through basic auth.  Using **username and password** directly would have some advantages:  * It is intuitive for the user who then just has to provide those just as they would when logging into OpenProject.  * No extra logic for token management necessary.  On the other hand using **API keys** has some advantages too, which is why we went for that:  * If compromised while saved on an insecure client the user only has to regenerate the API key instead of changing their password, too.  * They are naturally long and random which makes them invulnerable to dictionary attacks and harder to crack in general.  Most importantly users may not actually have a password to begin with. Specifically when they have registered through an OpenID Connect provider.  ## Cross-Origin Resource Sharing (CORS)  By default, the OpenProject API is _not_ responding with any CORS headers. If you want to allow cross-domain AJAX calls against your OpenProject instance, you need to enable CORS headers being returned.  Please see [our API settings documentation](https://www.openproject.org/docs/system-admin-guide/api-and-webhooks/) on how to selectively enable CORS.  ## Allowed HTTP methods  - `GET` - Get a single resource or collection of resources  - `POST` - Create a new resource or perform  - `PATCH` - Update a resource  - `DELETE` - Delete a resource  ## Compression  Responses are compressed if requested by the client. Currently [gzip](https://www.gzip.org/) and [deflate](https://tools.ietf.org/html/rfc1951) are supported. The client signals the desired compression by setting the [`Accept-Encoding` header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3). If no `Accept-Encoding` header is send, `Accept-Encoding: identity` is assumed which will result in the API responding uncompressed.

    The version of the OpenAPI document: 3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from auto_slopp.openproject.openapi_client.models.activity_comment_write_model import ActivityCommentWriteModel
from auto_slopp.openproject.openapi_client.models.activity_comment_write_model_comment import ActivityCommentWriteModelComment
from auto_slopp.openproject.openapi_client.models.activity_model import ActivityModel
from auto_slopp.openproject.openapi_client.models.activity_model_embedded import ActivityModelEmbedded
from auto_slopp.openproject.openapi_client.models.activity_model_links import ActivityModelLinks
from auto_slopp.openproject.openapi_client.models.add_watcher_request import AddWatcherRequest
from auto_slopp.openproject.openapi_client.models.attachment_model import AttachmentModel
from auto_slopp.openproject.openapi_client.models.attachment_model_digest import AttachmentModelDigest
from auto_slopp.openproject.openapi_client.models.attachment_model_links import AttachmentModelLinks
from auto_slopp.openproject.openapi_client.models.attachments_model import AttachmentsModel
from auto_slopp.openproject.openapi_client.models.attachments_model_all_of_embedded import AttachmentsModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.attachments_model_all_of_embedded_elements import AttachmentsModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.attachments_model_all_of_links import AttachmentsModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.available_assignees_model import AvailableAssigneesModel
from auto_slopp.openproject.openapi_client.models.available_assignees_model_all_of_embedded import AvailableAssigneesModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.available_assignees_model_all_of_embedded_elements import AvailableAssigneesModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.available_assignees_model_all_of_links import AvailableAssigneesModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.budget_model import BudgetModel
from auto_slopp.openproject.openapi_client.models.budget_model_links import BudgetModelLinks
from auto_slopp.openproject.openapi_client.models.categories_by_workspace_model import CategoriesByWorkspaceModel
from auto_slopp.openproject.openapi_client.models.categories_by_workspace_model_all_of_embedded import CategoriesByWorkspaceModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.categories_by_workspace_model_all_of_embedded_elements import CategoriesByWorkspaceModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.categories_by_workspace_model_all_of_links import CategoriesByWorkspaceModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.category_model import CategoryModel
from auto_slopp.openproject.openapi_client.models.category_model_links import CategoryModelLinks
from auto_slopp.openproject.openapi_client.models.collection_links import CollectionLinks
from auto_slopp.openproject.openapi_client.models.collection_model import CollectionModel
from auto_slopp.openproject.openapi_client.models.configuration_model import ConfigurationModel
from auto_slopp.openproject.openapi_client.models.create_views_request import CreateViewsRequest
from auto_slopp.openproject.openapi_client.models.create_views_request_links import CreateViewsRequestLinks
from auto_slopp.openproject.openapi_client.models.create_views_request_links_query import CreateViewsRequestLinksQuery
from auto_slopp.openproject.openapi_client.models.create_work_package_reminder_request import CreateWorkPackageReminderRequest
from auto_slopp.openproject.openapi_client.models.custom_action_model import CustomActionModel
from auto_slopp.openproject.openapi_client.models.custom_action_model_links import CustomActionModelLinks
from auto_slopp.openproject.openapi_client.models.custom_option_model import CustomOptionModel
from auto_slopp.openproject.openapi_client.models.custom_option_model_links import CustomOptionModelLinks
from auto_slopp.openproject.openapi_client.models.day_collection_model import DayCollectionModel
from auto_slopp.openproject.openapi_client.models.day_collection_model_all_of_embedded import DayCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.day_collection_model_all_of_links import DayCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.day_model import DayModel
from auto_slopp.openproject.openapi_client.models.day_model_links import DayModelLinks
from auto_slopp.openproject.openapi_client.models.document_model import DocumentModel
from auto_slopp.openproject.openapi_client.models.document_model_links import DocumentModelLinks
from auto_slopp.openproject.openapi_client.models.emoji_reaction_model import EmojiReactionModel
from auto_slopp.openproject.openapi_client.models.emoji_reaction_model_links import EmojiReactionModelLinks
from auto_slopp.openproject.openapi_client.models.emoji_reactions_model import EmojiReactionsModel
from auto_slopp.openproject.openapi_client.models.emoji_reactions_model_embedded import EmojiReactionsModelEmbedded
from auto_slopp.openproject.openapi_client.models.emoji_reactions_model_links import EmojiReactionsModelLinks
from auto_slopp.openproject.openapi_client.models.error_response import ErrorResponse
from auto_slopp.openproject.openapi_client.models.error_response_embedded import ErrorResponseEmbedded
from auto_slopp.openproject.openapi_client.models.error_response_embedded_details import ErrorResponseEmbeddedDetails
from auto_slopp.openproject.openapi_client.models.execute_custom_action_request import ExecuteCustomActionRequest
from auto_slopp.openproject.openapi_client.models.execute_custom_action_request_links import ExecuteCustomActionRequestLinks
from auto_slopp.openproject.openapi_client.models.execute_custom_action_request_links_work_package import ExecuteCustomActionRequestLinksWorkPackage
from auto_slopp.openproject.openapi_client.models.file_link_collection_read_model import FileLinkCollectionReadModel
from auto_slopp.openproject.openapi_client.models.file_link_collection_read_model_all_of_embedded import FileLinkCollectionReadModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.file_link_collection_read_model_all_of_links import FileLinkCollectionReadModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.file_link_collection_write_model import FileLinkCollectionWriteModel
from auto_slopp.openproject.openapi_client.models.file_link_collection_write_model_embedded import FileLinkCollectionWriteModelEmbedded
from auto_slopp.openproject.openapi_client.models.file_link_origin_data_model import FileLinkOriginDataModel
from auto_slopp.openproject.openapi_client.models.file_link_read_model import FileLinkReadModel
from auto_slopp.openproject.openapi_client.models.file_link_read_model_embedded import FileLinkReadModelEmbedded
from auto_slopp.openproject.openapi_client.models.file_link_read_model_links import FileLinkReadModelLinks
from auto_slopp.openproject.openapi_client.models.file_link_write_model import FileLinkWriteModel
from auto_slopp.openproject.openapi_client.models.file_link_write_model_links import FileLinkWriteModelLinks
from auto_slopp.openproject.openapi_client.models.file_link_write_model_links_one_of import FileLinkWriteModelLinksOneOf
from auto_slopp.openproject.openapi_client.models.file_link_write_model_links_one_of1 import FileLinkWriteModelLinksOneOf1
from auto_slopp.openproject.openapi_client.models.file_upload_form_metadata import FileUploadFormMetadata
from auto_slopp.openproject.openapi_client.models.formattable import Formattable
from auto_slopp.openproject.openapi_client.models.grid_collection_model import GridCollectionModel
from auto_slopp.openproject.openapi_client.models.grid_collection_model_all_of_embedded import GridCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.grid_read_model import GridReadModel
from auto_slopp.openproject.openapi_client.models.grid_read_model_links import GridReadModelLinks
from auto_slopp.openproject.openapi_client.models.grid_widget_model import GridWidgetModel
from auto_slopp.openproject.openapi_client.models.grid_write_model import GridWriteModel
from auto_slopp.openproject.openapi_client.models.grid_write_model_links import GridWriteModelLinks
from auto_slopp.openproject.openapi_client.models.group_collection_model import GroupCollectionModel
from auto_slopp.openproject.openapi_client.models.group_collection_model_all_of_embedded import GroupCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.group_collection_model_all_of_links import GroupCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.group_model import GroupModel
from auto_slopp.openproject.openapi_client.models.group_model_all_of_embedded import GroupModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.group_model_all_of_links import GroupModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.group_model_all_of_links_members import GroupModelAllOfLinksMembers
from auto_slopp.openproject.openapi_client.models.group_write_model import GroupWriteModel
from auto_slopp.openproject.openapi_client.models.group_write_model_links import GroupWriteModelLinks
from auto_slopp.openproject.openapi_client.models.help_text_collection_model import HelpTextCollectionModel
from auto_slopp.openproject.openapi_client.models.help_text_collection_model_all_of_embedded import HelpTextCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.help_text_collection_model_all_of_links import HelpTextCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.help_text_model import HelpTextModel
from auto_slopp.openproject.openapi_client.models.help_text_model_links import HelpTextModelLinks
from auto_slopp.openproject.openapi_client.models.hierarchy_item_collection_model import HierarchyItemCollectionModel
from auto_slopp.openproject.openapi_client.models.hierarchy_item_collection_model_all_of_embedded import HierarchyItemCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.hierarchy_item_collection_model_all_of_links import HierarchyItemCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.hierarchy_item_read_model import HierarchyItemReadModel
from auto_slopp.openproject.openapi_client.models.hierarchy_item_read_model_links import HierarchyItemReadModelLinks
from auto_slopp.openproject.openapi_client.models.link import Link
from auto_slopp.openproject.openapi_client.models.list_available_parent_project_candidates_model import ListAvailableParentProjectCandidatesModel
from auto_slopp.openproject.openapi_client.models.list_available_parent_project_candidates_model_all_of_embedded import ListAvailableParentProjectCandidatesModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.list_available_parent_project_candidates_model_all_of_embedded_elements import ListAvailableParentProjectCandidatesModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.list_available_parent_project_candidates_model_all_of_links import ListAvailableParentProjectCandidatesModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.list_reminders200_response import ListReminders200Response
from auto_slopp.openproject.openapi_client.models.list_reminders200_response_embedded import ListReminders200ResponseEmbedded
from auto_slopp.openproject.openapi_client.models.meeting_model import MeetingModel
from auto_slopp.openproject.openapi_client.models.meeting_model_links import MeetingModelLinks
from auto_slopp.openproject.openapi_client.models.membership_collection_model import MembershipCollectionModel
from auto_slopp.openproject.openapi_client.models.membership_collection_model_all_of_embedded import MembershipCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.membership_form_model import MembershipFormModel
from auto_slopp.openproject.openapi_client.models.membership_form_model_embedded import MembershipFormModelEmbedded
from auto_slopp.openproject.openapi_client.models.membership_form_model_embedded_validation_error import MembershipFormModelEmbeddedValidationError
from auto_slopp.openproject.openapi_client.models.membership_form_model_links import MembershipFormModelLinks
from auto_slopp.openproject.openapi_client.models.membership_read_model import MembershipReadModel
from auto_slopp.openproject.openapi_client.models.membership_read_model_embedded import MembershipReadModelEmbedded
from auto_slopp.openproject.openapi_client.models.membership_read_model_embedded_principal import MembershipReadModelEmbeddedPrincipal
from auto_slopp.openproject.openapi_client.models.membership_read_model_embedded_project import MembershipReadModelEmbeddedProject
from auto_slopp.openproject.openapi_client.models.membership_read_model_links import MembershipReadModelLinks
from auto_slopp.openproject.openapi_client.models.membership_schema_model import MembershipSchemaModel
from auto_slopp.openproject.openapi_client.models.membership_write_model import MembershipWriteModel
from auto_slopp.openproject.openapi_client.models.membership_write_model_links import MembershipWriteModelLinks
from auto_slopp.openproject.openapi_client.models.membership_write_model_meta import MembershipWriteModelMeta
from auto_slopp.openproject.openapi_client.models.news_create_model import NewsCreateModel
from auto_slopp.openproject.openapi_client.models.news_create_model_links import NewsCreateModelLinks
from auto_slopp.openproject.openapi_client.models.news_model import NewsModel
from auto_slopp.openproject.openapi_client.models.news_model_links import NewsModelLinks
from auto_slopp.openproject.openapi_client.models.non_working_day_collection_model import NonWorkingDayCollectionModel
from auto_slopp.openproject.openapi_client.models.non_working_day_collection_model_all_of_embedded import NonWorkingDayCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.non_working_day_collection_model_all_of_links import NonWorkingDayCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.non_working_day_model import NonWorkingDayModel
from auto_slopp.openproject.openapi_client.models.non_working_day_model_links import NonWorkingDayModelLinks
from auto_slopp.openproject.openapi_client.models.notification_collection_model import NotificationCollectionModel
from auto_slopp.openproject.openapi_client.models.notification_collection_model_all_of_embedded import NotificationCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.notification_collection_model_all_of_links import NotificationCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.notification_model import NotificationModel
from auto_slopp.openproject.openapi_client.models.notification_model_embedded import NotificationModelEmbedded
from auto_slopp.openproject.openapi_client.models.notification_model_links import NotificationModelLinks
from auto_slopp.openproject.openapi_client.models.o_auth_application_read_model import OAuthApplicationReadModel
from auto_slopp.openproject.openapi_client.models.o_auth_application_read_model_links import OAuthApplicationReadModelLinks
from auto_slopp.openproject.openapi_client.models.o_auth_client_credentials_read_model import OAuthClientCredentialsReadModel
from auto_slopp.openproject.openapi_client.models.o_auth_client_credentials_read_model_links import OAuthClientCredentialsReadModelLinks
from auto_slopp.openproject.openapi_client.models.o_auth_client_credentials_write_model import OAuthClientCredentialsWriteModel
from auto_slopp.openproject.openapi_client.models.offset_paginated_collection_links import OffsetPaginatedCollectionLinks
from auto_slopp.openproject.openapi_client.models.offset_paginated_collection_model import OffsetPaginatedCollectionModel
from auto_slopp.openproject.openapi_client.models.paginated_collection_model import PaginatedCollectionModel
from auto_slopp.openproject.openapi_client.models.paginated_collection_model_all_of_links import PaginatedCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.placeholder_user_collection_model import PlaceholderUserCollectionModel
from auto_slopp.openproject.openapi_client.models.placeholder_user_collection_model_all_of_embedded import PlaceholderUserCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.placeholder_user_collection_model_all_of_links import PlaceholderUserCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.placeholder_user_create_model import PlaceholderUserCreateModel
from auto_slopp.openproject.openapi_client.models.placeholder_user_model import PlaceholderUserModel
from auto_slopp.openproject.openapi_client.models.placeholder_user_model_all_of_links import PlaceholderUserModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.portfolio_collection_model import PortfolioCollectionModel
from auto_slopp.openproject.openapi_client.models.portfolio_collection_model_all_of_embedded import PortfolioCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.portfolio_collection_model_all_of_links import PortfolioCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.portfolio_model import PortfolioModel
from auto_slopp.openproject.openapi_client.models.portfolio_model_all_of_links import PortfolioModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.portfolio_model_all_of_links_ancestors import PortfolioModelAllOfLinksAncestors
from auto_slopp.openproject.openapi_client.models.portfolio_model_all_of_links_storages import PortfolioModelAllOfLinksStorages
from auto_slopp.openproject.openapi_client.models.post_model import PostModel
from auto_slopp.openproject.openapi_client.models.post_model_links import PostModelLinks
from auto_slopp.openproject.openapi_client.models.principal_collection_model import PrincipalCollectionModel
from auto_slopp.openproject.openapi_client.models.principal_collection_model_all_of_embedded import PrincipalCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.principal_collection_model_all_of_embedded_elements import PrincipalCollectionModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.principal_model import PrincipalModel
from auto_slopp.openproject.openapi_client.models.principal_model_links import PrincipalModelLinks
from auto_slopp.openproject.openapi_client.models.priority_collection_model import PriorityCollectionModel
from auto_slopp.openproject.openapi_client.models.priority_collection_model_all_of_embedded import PriorityCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.priority_collection_model_all_of_links import PriorityCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.priority_collection_model_all_of_links_self import PriorityCollectionModelAllOfLinksSelf
from auto_slopp.openproject.openapi_client.models.priority_model import PriorityModel
from auto_slopp.openproject.openapi_client.models.priority_model_links import PriorityModelLinks
from auto_slopp.openproject.openapi_client.models.program_collection_model import ProgramCollectionModel
from auto_slopp.openproject.openapi_client.models.program_collection_model_all_of_embedded import ProgramCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.program_collection_model_all_of_links import ProgramCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.program_model import ProgramModel
from auto_slopp.openproject.openapi_client.models.program_model_all_of_links import ProgramModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.program_model_all_of_links_ancestors import ProgramModelAllOfLinksAncestors
from auto_slopp.openproject.openapi_client.models.program_model_all_of_links_storages import ProgramModelAllOfLinksStorages
from auto_slopp.openproject.openapi_client.models.project_collection_model import ProjectCollectionModel
from auto_slopp.openproject.openapi_client.models.project_collection_model_all_of_embedded import ProjectCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.project_collection_model_all_of_links import ProjectCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.project_configuration_model import ProjectConfigurationModel
from auto_slopp.openproject.openapi_client.models.project_model import ProjectModel
from auto_slopp.openproject.openapi_client.models.project_model_all_of_links import ProjectModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.project_model_all_of_links_ancestors import ProjectModelAllOfLinksAncestors
from auto_slopp.openproject.openapi_client.models.project_model_all_of_links_storages import ProjectModelAllOfLinksStorages
from auto_slopp.openproject.openapi_client.models.project_phase_definition_collection_model import ProjectPhaseDefinitionCollectionModel
from auto_slopp.openproject.openapi_client.models.project_phase_definition_collection_model_all_of_embedded import ProjectPhaseDefinitionCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.project_phase_definition_collection_model_all_of_links import ProjectPhaseDefinitionCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.project_phase_definition_model import ProjectPhaseDefinitionModel
from auto_slopp.openproject.openapi_client.models.project_phase_definition_model_links import ProjectPhaseDefinitionModelLinks
from auto_slopp.openproject.openapi_client.models.project_phase_model import ProjectPhaseModel
from auto_slopp.openproject.openapi_client.models.project_phase_model_links import ProjectPhaseModelLinks
from auto_slopp.openproject.openapi_client.models.project_storage_collection_model import ProjectStorageCollectionModel
from auto_slopp.openproject.openapi_client.models.project_storage_collection_model_all_of_embedded import ProjectStorageCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.project_storage_collection_model_all_of_links import ProjectStorageCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.project_storage_model import ProjectStorageModel
from auto_slopp.openproject.openapi_client.models.project_storage_model_links import ProjectStorageModelLinks
from auto_slopp.openproject.openapi_client.models.query_column_model import QueryColumnModel
from auto_slopp.openproject.openapi_client.models.query_create_form import QueryCreateForm
from auto_slopp.openproject.openapi_client.models.query_filter_instance_model import QueryFilterInstanceModel
from auto_slopp.openproject.openapi_client.models.query_filter_instance_model_links import QueryFilterInstanceModelLinks
from auto_slopp.openproject.openapi_client.models.query_filter_instance_schema_model import QueryFilterInstanceSchemaModel
from auto_slopp.openproject.openapi_client.models.query_filter_instance_schema_model_links import QueryFilterInstanceSchemaModelLinks
from auto_slopp.openproject.openapi_client.models.query_filter_model import QueryFilterModel
from auto_slopp.openproject.openapi_client.models.query_model import QueryModel
from auto_slopp.openproject.openapi_client.models.query_model_links import QueryModelLinks
from auto_slopp.openproject.openapi_client.models.query_operator_model import QueryOperatorModel
from auto_slopp.openproject.openapi_client.models.query_sort_by_model import QuerySortByModel
from auto_slopp.openproject.openapi_client.models.query_update_form import QueryUpdateForm
from auto_slopp.openproject.openapi_client.models.relation_collection_model import RelationCollectionModel
from auto_slopp.openproject.openapi_client.models.relation_collection_model_all_of_embedded import RelationCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.relation_collection_model_all_of_links import RelationCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.relation_read_model import RelationReadModel
from auto_slopp.openproject.openapi_client.models.relation_read_model_embedded import RelationReadModelEmbedded
from auto_slopp.openproject.openapi_client.models.relation_read_model_links import RelationReadModelLinks
from auto_slopp.openproject.openapi_client.models.relation_write_model import RelationWriteModel
from auto_slopp.openproject.openapi_client.models.relation_write_model_links import RelationWriteModelLinks
from auto_slopp.openproject.openapi_client.models.reminder_model import ReminderModel
from auto_slopp.openproject.openapi_client.models.reminder_model_links import ReminderModelLinks
from auto_slopp.openproject.openapi_client.models.revision_model import RevisionModel
from auto_slopp.openproject.openapi_client.models.revision_model_links import RevisionModelLinks
from auto_slopp.openproject.openapi_client.models.role_model import RoleModel
from auto_slopp.openproject.openapi_client.models.role_model_links import RoleModelLinks
from auto_slopp.openproject.openapi_client.models.root_model import RootModel
from auto_slopp.openproject.openapi_client.models.root_model_links import RootModelLinks
from auto_slopp.openproject.openapi_client.models.schema_model import SchemaModel
from auto_slopp.openproject.openapi_client.models.schema_model_links import SchemaModelLinks
from auto_slopp.openproject.openapi_client.models.schema_property_model import SchemaPropertyModel
from auto_slopp.openproject.openapi_client.models.show_or_validate_form_request import ShowOrValidateFormRequest
from auto_slopp.openproject.openapi_client.models.status_collection_model import StatusCollectionModel
from auto_slopp.openproject.openapi_client.models.status_collection_model_all_of_embedded import StatusCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.status_model import StatusModel
from auto_slopp.openproject.openapi_client.models.status_model_links import StatusModelLinks
from auto_slopp.openproject.openapi_client.models.storage_collection_model import StorageCollectionModel
from auto_slopp.openproject.openapi_client.models.storage_collection_model_all_of_embedded import StorageCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.storage_collection_model_all_of_links import StorageCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.storage_file_model import StorageFileModel
from auto_slopp.openproject.openapi_client.models.storage_file_model_all_of_links import StorageFileModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.storage_file_upload_link_model import StorageFileUploadLinkModel
from auto_slopp.openproject.openapi_client.models.storage_file_upload_link_model_links import StorageFileUploadLinkModelLinks
from auto_slopp.openproject.openapi_client.models.storage_file_upload_preparation_model import StorageFileUploadPreparationModel
from auto_slopp.openproject.openapi_client.models.storage_files_model import StorageFilesModel
from auto_slopp.openproject.openapi_client.models.storage_folder_write_model import StorageFolderWriteModel
from auto_slopp.openproject.openapi_client.models.storage_read_model import StorageReadModel
from auto_slopp.openproject.openapi_client.models.storage_read_model_embedded import StorageReadModelEmbedded
from auto_slopp.openproject.openapi_client.models.storage_read_model_links import StorageReadModelLinks
from auto_slopp.openproject.openapi_client.models.storage_write_model import StorageWriteModel
from auto_slopp.openproject.openapi_client.models.storage_write_model_links import StorageWriteModelLinks
from auto_slopp.openproject.openapi_client.models.time_entry_activity_model import TimeEntryActivityModel
from auto_slopp.openproject.openapi_client.models.time_entry_activity_model_embedded import TimeEntryActivityModelEmbedded
from auto_slopp.openproject.openapi_client.models.time_entry_activity_model_links import TimeEntryActivityModelLinks
from auto_slopp.openproject.openapi_client.models.time_entry_collection_model import TimeEntryCollectionModel
from auto_slopp.openproject.openapi_client.models.time_entry_collection_model_all_of_embedded import TimeEntryCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.time_entry_collection_model_all_of_links import TimeEntryCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.time_entry_model import TimeEntryModel
from auto_slopp.openproject.openapi_client.models.time_entry_model_all_of_links import TimeEntryModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.toggle_activity_emoji_reaction_request import ToggleActivityEmojiReactionRequest
from auto_slopp.openproject.openapi_client.models.type_model import TypeModel
from auto_slopp.openproject.openapi_client.models.type_model_links import TypeModelLinks
from auto_slopp.openproject.openapi_client.models.types_by_workspace_model import TypesByWorkspaceModel
from auto_slopp.openproject.openapi_client.models.types_by_workspace_model_all_of_embedded import TypesByWorkspaceModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.types_by_workspace_model_all_of_embedded_elements import TypesByWorkspaceModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.types_by_workspace_model_all_of_links import TypesByWorkspaceModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.update_document_request import UpdateDocumentRequest
from auto_slopp.openproject.openapi_client.models.update_document_request_description import UpdateDocumentRequestDescription
from auto_slopp.openproject.openapi_client.models.update_reminder_request import UpdateReminderRequest
from auto_slopp.openproject.openapi_client.models.update_user_preferences_request import UpdateUserPreferencesRequest
from auto_slopp.openproject.openapi_client.models.user_collection_model import UserCollectionModel
from auto_slopp.openproject.openapi_client.models.user_collection_model_all_of_embedded import UserCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.user_collection_model_all_of_links import UserCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.user_create_model import UserCreateModel
from auto_slopp.openproject.openapi_client.models.user_model import UserModel
from auto_slopp.openproject.openapi_client.models.user_model_all_of_links import UserModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.values_property_model import ValuesPropertyModel
from auto_slopp.openproject.openapi_client.models.values_property_model_links import ValuesPropertyModelLinks
from auto_slopp.openproject.openapi_client.models.version_collection_model import VersionCollectionModel
from auto_slopp.openproject.openapi_client.models.version_collection_model_all_of_embedded import VersionCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.version_collection_model_all_of_links import VersionCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.version_read_model import VersionReadModel
from auto_slopp.openproject.openapi_client.models.version_read_model_all_of_links import VersionReadModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.version_write_model import VersionWriteModel
from auto_slopp.openproject.openapi_client.models.version_write_model_all_of_links import VersionWriteModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.versions_by_workspace_model import VersionsByWorkspaceModel
from auto_slopp.openproject.openapi_client.models.versions_by_workspace_model_all_of_embedded import VersionsByWorkspaceModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.versions_by_workspace_model_all_of_embedded_elements import VersionsByWorkspaceModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.versions_by_workspace_model_all_of_links import VersionsByWorkspaceModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.watchers_model import WatchersModel
from auto_slopp.openproject.openapi_client.models.watchers_model_all_of_embedded import WatchersModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.watchers_model_all_of_embedded_elements import WatchersModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.watchers_model_all_of_links import WatchersModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.week_day_collection_model import WeekDayCollectionModel
from auto_slopp.openproject.openapi_client.models.week_day_collection_model_all_of_embedded import WeekDayCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.week_day_collection_model_all_of_links import WeekDayCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.week_day_collection_write_model import WeekDayCollectionWriteModel
from auto_slopp.openproject.openapi_client.models.week_day_collection_write_model_embedded import WeekDayCollectionWriteModelEmbedded
from auto_slopp.openproject.openapi_client.models.week_day_collection_write_model_embedded_elements_inner import WeekDayCollectionWriteModelEmbeddedElementsInner
from auto_slopp.openproject.openapi_client.models.week_day_model import WeekDayModel
from auto_slopp.openproject.openapi_client.models.week_day_self_link_model import WeekDaySelfLinkModel
from auto_slopp.openproject.openapi_client.models.week_day_write_model import WeekDayWriteModel
from auto_slopp.openproject.openapi_client.models.wiki_page_model import WikiPageModel
from auto_slopp.openproject.openapi_client.models.wiki_page_model_links import WikiPageModelLinks
from auto_slopp.openproject.openapi_client.models.work_package_form_model import WorkPackageFormModel
from auto_slopp.openproject.openapi_client.models.work_package_form_model_embedded import WorkPackageFormModelEmbedded
from auto_slopp.openproject.openapi_client.models.work_package_form_model_links import WorkPackageFormModelLinks
from auto_slopp.openproject.openapi_client.models.work_package_model import WorkPackageModel
from auto_slopp.openproject.openapi_client.models.work_package_model_all_of_links import WorkPackageModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.work_package_model_all_of_links_ancestors import WorkPackageModelAllOfLinksAncestors
from auto_slopp.openproject.openapi_client.models.work_package_model_all_of_links_children import WorkPackageModelAllOfLinksChildren
from auto_slopp.openproject.openapi_client.models.work_package_model_all_of_links_custom_actions import WorkPackageModelAllOfLinksCustomActions
from auto_slopp.openproject.openapi_client.models.work_package_patch_model import WorkPackagePatchModel
from auto_slopp.openproject.openapi_client.models.work_package_schema_model import WorkPackageSchemaModel
from auto_slopp.openproject.openapi_client.models.work_package_schema_model_links import WorkPackageSchemaModelLinks
from auto_slopp.openproject.openapi_client.models.work_package_write_model import WorkPackageWriteModel
from auto_slopp.openproject.openapi_client.models.work_package_write_model_links import WorkPackageWriteModelLinks
from auto_slopp.openproject.openapi_client.models.work_package_write_model_meta import WorkPackageWriteModelMeta
from auto_slopp.openproject.openapi_client.models.work_packages_model import WorkPackagesModel
from auto_slopp.openproject.openapi_client.models.work_packages_model_all_of_embedded import WorkPackagesModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.work_packages_model_all_of_links import WorkPackagesModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.workspace_collection_model import WorkspaceCollectionModel
from auto_slopp.openproject.openapi_client.models.workspace_collection_model_all_of_embedded import WorkspaceCollectionModelAllOfEmbedded
from auto_slopp.openproject.openapi_client.models.workspace_collection_model_all_of_embedded_elements import WorkspaceCollectionModelAllOfEmbeddedElements
from auto_slopp.openproject.openapi_client.models.workspace_collection_model_all_of_links import WorkspaceCollectionModelAllOfLinks
from auto_slopp.openproject.openapi_client.models.workspaces_schema_model import WorkspacesSchemaModel
from auto_slopp.openproject.openapi_client.models.workspaces_schema_model_attribute_groups_inner import WorkspacesSchemaModelAttributeGroupsInner
from auto_slopp.openproject.openapi_client.models.workspaces_schema_model_links import WorkspacesSchemaModelLinks
from auto_slopp.openproject.openapi_client.models.workspaces_schema_model_links_self import WorkspacesSchemaModelLinksSelf

