#!/bin/bash

# Create directories for each repository
echo "Running creator.sh"

# Read repositories from repos.txt
while read -r repo; do
    # Skip comments and empty lines
    [[ $repo =~ ^[[:space:]]*# ]] && continue
    [[ -z "$repo" ]] && continue
    
    # Expand $HOME and other variables
    repo=$(eval echo "$repo")
    
    if [ ! -d "$repo" ]; then
        echo "Repository not found: $repo"
        continue
    fi
    
    # Get repository name
    repo_name=$(basename "$repo")
    repo_name=$(echo "$repo_name" | sed 's/[^a-zA-Z0-9._-]/_/g')
    
    echo "Creating directory for: $repo_name"
    
    # Create directory structure
    mkdir -p "$repo_name"/{tasks,logs,state}
    
    # Create README if it doesn't exist
    if [ ! -f "$repo_name/README.md" ]; then
        cat > "$repo_name/README.md" << EOF
# $repo_name

Automation files for repository: $repo_path

## Directories
- tasks/ - Task files for processing
- logs/ - Log files
- state/ - State tracking

Generated by Repository Automation System
EOF
    fi
done < repos.txt