#!/bin/bash

# creator.sh - Creates directories in this repository for each repo in the repo directory
# Sets up the directory structure for the automation system

# Load common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# Function to get list of repositories
get_repositories() {
    local repos_file="$AUTOMATION_ROOT/repos.txt"
    
    if [ ! -f "$repos_file" ]; then
        log_error "Repository list file not found: $repos_file"
        return 1
    fi
    
    # Read and expand repository paths
    local repos=()
    while IFS= read -r line; do
        # Skip empty lines and comments
        [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
        
        # Expand variables like $HOME
        local expanded_path=$(eval echo "$line")
        
        if [ -d "$expanded_path" ]; then
            repos+=("$expanded_path")
        else
            log_warn "Repository directory not found: $expanded_path"
        fi
    done < "$repos_file"
    
    echo "${repos[@]}"
}

# Function to get repository name from path
get_repo_name() {
    local repo_path="$1"
    
    # Extract the last directory name from the path
    local repo_name=$(basename "$repo_path")
    
    # Sanitize the name (remove special characters, replace spaces)
    repo_name=$(echo "$repo_name" | sed 's/[^a-zA-Z0-9._-]/_/g')
    
    echo "$repo_name"
}

# Function to create directory for a repository
create_repo_directory() {
    local repo_path="$1"
    local repo_name=$(get_repo_name "$repo_path")
    local target_dir="$AUTOMATION_ROOT/$repo_name"
    
    log_info "Creating directory for repository: $repo_name (from $repo_path)"
    
    # Check if directory already exists
    if [ -d "$target_dir" ]; then
        log_info "Directory already exists: $target_dir"
        return 0
    fi
    
    # Create the directory
    if mkdir -p "$target_dir"; then
        log_info "Created directory: $target_dir"
        
        # Create a README file with repository information
        create_repo_readme "$target_dir" "$repo_path" "$repo_name"
        
        # Create initial subdirectories
        create_repo_subdirectories "$target_dir"
        
        return 0
    else
        log_error "Failed to create directory: $target_dir"
        return 1
    fi
}

# Function to create README for repository directory
create_repo_readme() {
    local target_dir="$1"
    local repo_path="$2"
    local repo_name="$3"
    
    local readme_file="$target_dir/README.md"
    
    cat > "$readme_file" << EOF
# $repo_name

This directory contains automation files for the repository located at:
\`$repo_path\`

## Directory Structure

- \`tasks/\` - Task files for processing by planner.sh
- \`logs/\` - Log files specific to this repository
- \`state/\` - State files and tracking information

## Automation

This directory is managed by the Repository Automation System.

- **creator.sh** - Creates this directory structure
- **planner.sh** - Processes task files and generates bead tasks
- **implementer.sh** - Implements bead tasks in the repository

## Generated Files

Files in this directory are automatically generated and managed by the automation system. Manual edits may be overwritten.

---
*Generated by Repository Automation System on $(date)*
EOF

    log_info "Created README: $readme_file"
}

# Function to create subdirectories for repository
create_repo_subdirectories() {
    local target_dir="$1"
    
    local subdirs=(
        "tasks"
        "logs"
        "state"
    )
    
    for subdir in "${subdirs[@]}"; do
        local subdir_path="$target_dir/$subdir"
        
        if mkdir -p "$subdir_path"; then
            log_debug "Created subdirectory: $subdir_path"
            
            # Create .gitkeep file to ensure directory is tracked
            touch "$subdir_path/.gitkeep"
        else
            log_warn "Failed to create subdirectory: $subdir_path"
        fi
    done
}

# Function to process all repositories
process_all_repositories() {
    log_info "Starting to create directories for all repositories"
    
    local repositories=($(get_repositories))
    
    if [ ${#repositories[@]} -eq 0 ]; then
        log_warn "No repositories found to process"
        return 0
    fi
    
    log_info "Found ${#repositories[@]} repositories to process"
    
    local created_dirs=()
    local failed_dirs=()
    
    for repo in "${repositories[@]}"; do
        local repo_name=$(get_repo_name "$repo")
        
        if create_repo_directory "$repo"; then
            created_dirs+=("$repo_name")
        else
            failed_dirs+=("$repo_name")
        fi
    done
    
    # Log summary
    log_info "Creator completed. Created: ${#created_dirs[@]}, Failed: ${#failed_dirs[@]}"
    
    if [ ${#created_dirs[@]} -gt 0 ]; then
        log_info "Created directories: ${created_dirs[*]}"
    fi
    
    if [ ${#failed_dirs[@]} -gt 0 ]; then
        log_error "Failed to create directories: ${failed_dirs[*]}"
        return 1
    fi
    
    return 0
}

# Function to validate repository directories
validate_repository_directories() {
    log_info "Validating repository directories"
    
    local repositories=($(get_repositories))
    local validation_errors=()
    
    for repo in "${repositories[@]}"; do
        local repo_name=$(get_repo_name "$repo")
        local target_dir="$AUTOMATION_ROOT/$repo_name"
        
        # Check if directory exists
        if [ ! -d "$target_dir" ]; then
            validation_errors+=("Missing directory: $repo_name")
            continue
        fi
        
        # Check if subdirectories exist
        local required_subdirs=("tasks" "logs" "state")
        for subdir in "${required_subdirs[@]}"; do
            if [ ! -d "$target_dir/$subdir" ]; then
                validation_errors+=("Missing subdirectory: $repo_name/$subdir")
            fi
        done
        
        # Check if README exists
        if [ ! -f "$target_dir/README.md" ]; then
            validation_errors+=("Missing README: $repo_name")
        fi
    done
    
    if [ ${#validation_errors[@]} -gt 0 ]; then
        log_error "Validation errors found:"
        for error in "${validation_errors[@]}"; do
            log_error "  - $error"
        done
        return 1
    fi
    
    log_info "All repository directories validated successfully"
    return 0
}

# Main execution function
main() {
    init_common
    
    # Validate dependencies
    validate_dependencies "mkdir" "basename" || exit 1
    
    # Process all repositories
    if process_all_repositories; then
        # Validate the created directories
        validate_repository_directories
    else
        log_error "Failed to process all repositories"
        exit 1
    fi
}

# Run main function if script is executed directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi