#!/bin/bash

# Create task directories for each repository using YAML configuration
# Set script name for logging identification
SCRIPT_NAME="creator"

# Load utilities and configuration first
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/utils.sh"
source "$SCRIPT_DIR/../config.sh"

# Set up error handling
setup_error_handling

log "INFO" "Starting creator.sh"
log "INFO" "Using managed_repo_path: $MANAGED_REPO_PATH"
log "INFO" "Using managed_repo_task_path: $MANAGED_REPO_TASK_PATH"

# Validate required environment variables
validate_env_vars MANAGED_REPO_PATH MANAGED_REPO_TASK_PATH

# Check if directories exist and are accessible
check_directory "$MANAGED_REPO_PATH" "managed_repo_path"

# Ensure repository is up to date before proceeding
log "INFO" "Updating repository with git pull..."
safe_git "pull"
log "SUCCESS" "Repository updated successfully"

# Create managed_repo_task_path if it doesn't exist
if [ ! -d "$MANAGED_REPO_TASK_PATH" ]; then
    log "INFO" "Creating managed_repo_task_path: $MANAGED_REPO_TASK_PATH"
    safe_execute "mkdir -p \"$MANAGED_REPO_TASK_PATH\""
    
    # Initialize as git repository if not already
    cd "$MANAGED_REPO_TASK_PATH"
    if [ ! -d .git ]; then
        safe_git "init"
        log "INFO" "Initialized git repository in $MANAGED_REPO_TASK_PATH"
    fi
fi

# Track if any directories were created
DIRECTORIES_CREATED=false

# Process each subdirectory in managed_repo_path
for repo_dir in "$MANAGED_REPO_PATH"/*; do
    if [ ! -d "$repo_dir" ]; then
        continue
    fi
    
    # Get repository name
    repo_name=$(basename "$repo_dir")
    log "INFO" "Processing repository: $repo_name"
    
    # Create corresponding directory in managed_repo_task_path
    task_dir="$MANAGED_REPO_TASK_PATH/$repo_name"
    
    if [ ! -d "$task_dir" ]; then
        log "INFO" "Creating task directory: $task_dir"
        safe_execute "mkdir -p \"$task_dir\""
        
        # Add .gitkeep file so directory can be tracked
        touch "$task_dir/.gitkeep"
        
        # Create README if it doesn't exist
        if [ ! -f "$task_dir/README.md" ]; then
            cat > "$task_dir/README.md" << EOF
# $repo_name

Task files for repository: $repo_name

## Usage
- Place task description files in this directory
- Files will be processed by planner.sh
- Processed files will be renamed with .used suffix

## Directory Structure
- .gitkeep - Ensures directory is tracked in git
- *.txt - Task description files (to be processed)
- *.used - Already processed task files

Generated by Repository Automation System
EOF
        fi
        
        DIRECTORIES_CREATED=true
        log "SUCCESS" "Created task directory for: $repo_name"
    else
        log "INFO" "Task directory already exists: $task_dir"
    fi
done

# Commit and push changes if any directories were created
log "INFO" "Committing new task directories..."
cd "$MANAGED_REPO_TASK_PATH"
safe_git "add ."
safe_git "commit -m \"Add task directories for repositories by creator.sh\"" || true

# Handle potential push rejections by pulling first if needed
log "INFO" "Pushing changes to remote..."
if ! safe_git "push"; then
    log "WARNING" "Push failed, attempting to pull remote changes first..."
    safe_git "pull --rebase"
    log "INFO" "Retrying push after pulling remote changes..."
    if ! safe_git "push"; then
        log "ERROR" "Push failed even after pulling remote changes. Manual intervention may be required."
        exit 1
    fi
fi
log "SUCCESS" "Task directories committed and pushed."

script_success
