name: Lint

on:
  push:
    branches: [ main, rework/python ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Install dependencies
      run: make dev-install

    - name: Run linting checks
      run: make lint